version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and start container
          command: docker-compose up -d

      - run:
          name: Run tests
          command: |
            docker exec -it transport-network-analysis bash -c "python setup.py test"
            docker cp transport-network-analysis:/Transport-Network-Analysis/htmlcov /tmp/artifacts

      - run:
          name: Build docs
          command: |
            docker exec -it transport-network-analysis bash -c "python setup.py docs"
            docker cp transport-network-analysis:/Transport-Network-Analysis/docs/_build/html /tmp/artifacts/docs

      - run:
          name: Generate coverage badge
          command: |
            docker exec -it transport-network-analysis bash -c "pip install coverage coverage-badge"
            docker exec -it transport-network-analysis bash -c "coverage-badge -o coverage.svg"
            docker cp transport-network-analysis:/Transport-Network-Analysis/coverage.svg /tmp/artifacts/

      - store_artifacts:
          path: /tmp/artifacts

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
