version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - run:
          name: Build container
          command: docker build -t transport-network-analysis .
  test:
    docker:
      - image: continuumio/anaconda3
    steps:
      - checkout

      - run:
          name: Install requirements
          command: |
            pip install -r ./requirements.txt --quiet
            conda install pyproj
            pip install -e .

      - run:
          name: Run tests
          command: |
            python setup.py test
            echo printing the current working environment
            echo $PWD
            ls
            mv htmlcov /tmp/artifacts

      - run:
          name: Build docs
          command: |
            python setup.py docs
            mv docs/_build/html /tmp/artifacts/docs

      - run:
          name: Generate coverage badge
          command: |
            coverage-badge -o coverage.svg
            mv coverage.svg /tmp/artifacts/

      - store_artifacts:
          path: /tmp/artifacts

workflows:
  version: 2
  test:
    jobs:
#      - build:
#          filters:
#            tags:
#              only: /.*/
      - test:
          requires:
            - build
          filters:
            tags:
              only: /.*/
